{% set name = "motmetrics" %}
{% set version = "1.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a777d5ab611cee008ae2c1acc39c7048d2b0b2eafed0f0f1ae473f35ebe34b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.12.1
    - pandas >=0.23.1
    - python >=3.6
    - scipy >=0.19.0
    - xmltodict >=0.12.0



test:
  imports:
    - motmetrics
    - motmetrics.apps
  commands:
    - pip check
  requires:
    - pip
    - flake8
    - flake8-import-order
    - pytest
    - pytest-benchmark

about:
  home: https://github.com/cheind/py-motmetrics
  summary: Metrics for multiple object tracker benchmarking.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - quinnwinters
    - AndrewGoldstein
    - cinabars
